#skip = True
import subprocess, sys, os, OpenScad as vc
import trimesh
import numpy as np
import random

title = "Cage match. Can LLMs design interlocking parts for 3D printing?"

prompt = """

I would like you to generate a cage of internal size 350 x 350 x 700 mm. 

The cage should feature an all-around grid of 10mm thick bars, each with a square cross section. No thinner, no thicker.

The gap between bars should be between 5cm and 10cm, and uniform all over the model.

The cage needs to be split into parts that can be 3D printed on a 3D printer, with a build area
of 400x400x50mm.

The cage assembly should be held together by 4 x M6 threaded rods threaded through the middle
of the 4 vertical corner bars. You do not need to carve a female thread or nut slots into your parts,
but should ensure that a rod fits with adequete clearence into every hole. Use no additional connectors. Do not include
a door or lid.

Generate all parts that are needed for this project. They should be:
- ready to slice
- print without supports.
- orientated such that they fit within the build volume
- sitting on z=0 plane.
- not going to fall over during printing.
- valid shapes - watertight, closed solids with no self intersections.
- As few parts as possible.
- Use as little build volume of the 3D printer as possible.

For each part file, you may provide an STL file, or OpenSCAD file that generates it, or a python script that 
generates either the OpenSCAD or the STL. Provide all parts in one go into the supplied output structure.

For each part, include a rigid transform matrix (4x4 row major) that shows where the part sits in 3D space when assembled, in
your assembled 3D space, the cage sits on the z=0 plane and centred in x & y around 0,0.
Take care to get this projection right as it will be used to test whether the parts fit together correctly. 

"""

structure = {
  "type": "object",
  "properties": {
    "reasoning": {
      "type": "string"
    },
    "parts": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "fileContents": {
            "type":
            "string",
            "description":
            "Either a raw STL file (first word is 'solid'), "
            "a valid OpenSCAD file that generates the STL file."
            "a Python script that when run, outputs the STL file to stdout."
          },
          "fileType": {
            "type": "string",
            "enum": ["STL", "OpenSCAD", "Python Generating OpenSCAD", "Python Generating STL"],
            "description": "The type of file generated by the AI"
          },
          "transform": {
            "type": "array",
            "items": {
              "type":
              "number",
              "description":
              "The 4x4 transform matrix for this part. Must be a rigid transform (no scale or skew)."
            }
          }
        },
        "required": ["fileContents", "transform", "fileType"],
        "additionalProperties": False,
        "propertyOrdering": ["fileContents", "transform", "fileType"]
      }
    }
  },
  "required": ["parts", "reasoning"],
  "propertyOrdering": ["reasoning", "parts"],
  "additionalProperties": False
}

extraGradeAnswerRuns = [1, 2, 3, 4, 5, 6, 7, 8]
earlyFail = False


def _file_content_changed(filepath: str, new_content: str) -> bool:
  """Check if file doesn't exist or has different content than new_content."""
  if not os.path.exists(filepath):
    return True
  try:
    with open(filepath, "r", encoding="utf-8") as f:
      return f.read() != new_content
  except Exception:
    return True


def _write_if_changed(filepath: str, content: str) -> bool:
  """Write content to file only if it changed. Returns True if file was written."""
  if _file_content_changed(filepath, content):
    with open(filepath, "w", encoding="utf-8") as f:
      f.write(content)
    return True
  return False


def gradeAnswer(answer: dict, subPass: int, aiEngineName: str):
  global earlyFail
  score = 0
  bugs = ""
  import scad_format

  if "parts" not in answer:
    return 0, "Answer did not contain a 'parts' key."

  if len(answer["parts"]) > 10:
    return 0, "Answer contained too many parts. 10 is the minimum and optimum."

  if len(answer["parts"]) < 10:
    return 0, "Answer contained too few parts. 10 is the minimum possible."

  if subPass == 0:
    any_posed_changed = False
    for partIndex, part in enumerate(answer["parts"]):
      partName = "29_" + str(partIndex) + "_" + aiEngineName
      needs_regenerate = False

      # Determine source file path and check if content changed
      if part["fileType"].lower() == "stl":
        source_path = "results/" + partName + ".stl"
        needs_regenerate = _write_if_changed(source_path, part["fileContents"])

      elif part["fileType"].lower() == "openscad":
        source_path = "results/" + partName + ".scad"
        formatted = part["fileContents"]
        formatted = scad_format.format(formatted, vc.formatConfig)
        needs_regenerate = _write_if_changed(source_path, formatted)

      elif part["fileType"].lower() == "python generating openscad":
        source_path = "results/" + partName + ".py"
        needs_regenerate = _write_if_changed(source_path, part["fileContents"])

        if needs_regenerate:
          try:
            subprocess.run(sys.executable, [partName + ".py"],
                           stdout=open("results/" + partName + ".scad", "w", encoding="utf-8"),
                           cwd="results")
          except Exception as e:
            bugs += "Python generating OpenSCAD for " + partName + " failed due to " + str(
              e) + "<br>"

          scad_format.format_file("results/" + partName + ".scad", "results/" + partName + ".scad",
                                  vc.formatConfig)

      elif part["fileType"].lower() == "python generating stl":
        source_path = "results/" + partName + ".py"
        needs_regenerate = _write_if_changed(source_path, part["fileContents"])

        if needs_regenerate:
          try:
            subprocess.run(sys.executable, ["results/" + partName + ".py"],
                           stdout=open("results/" + partName + ".stl", "w", encoding="utf-8"),
                           cwd="results")
          except Exception as e:
            bugs += "Python generating STL for " + partName + " failed due to " + str(e) + "<br>"
      else:
        bugs += "Unknown file type '" + part["fileType"] + "' for " + partName + "<br>"

      # Generate STL from OpenSCAD if needed
      if os.path.exists("results/" + partName + ".scad") and (
          needs_regenerate or not os.path.exists("results/" + partName + ".stl")):
        try:
          subprocess.run([vc.openScadPath, partName + ".scad", "-o", partName + ".stl"],
                         cwd="results")
        except Exception as e:
          bugs += "OpenSCAD failed to generate STL for " + partName + " due to " + str(e) + "<br>"

      # Generate posed STL if needed
      posed_scad_content = f"""
    multmatrix([{part["transform"][0:4]}, 
                {part["transform"][4:8]}, 
                {part["transform"][8:12]}, 
                {part["transform"][12:16]}]) import("{partName}.stl");
                        """
      posed_scad_path = "results/" + partName + "_posed.scad"
      posed_changed = _write_if_changed(posed_scad_path,
                                        scad_format.format(posed_scad_content, vc.formatConfig))

      if os.path.exists("results/" + partName + ".stl") and bugs == "" and (
          needs_regenerate or posed_changed
          or not os.path.exists("results/" + partName + "_posed.stl")):
        try:
          subprocess.run([vc.openScadPath, partName + "_posed.scad", "-o", partName + "_posed.stl"],
                         cwd="results")
        except Exception as e:
          bugs += "OpenSCAD failed to generate posed STL for " + partName + " due to " + str(
            e) + "<br>"

      if needs_regenerate or posed_changed:
        any_posed_changed = True

    # Generate fullposed assembly
    colourNames = [
      "Red", "Green", "Blue", "Yellow", "Cyan", "Magenta", "Brown", "White", "Orange", "Grey"
    ]
    fullposed_scad_content = ""
    for partIndex, part in enumerate(answer["parts"]):
      partName = "29_" + str(partIndex) + "_" + str(aiEngineName)
      fullposed_scad_content += f"color(\"{colourNames[partIndex]}\") import(\"{partName}_posed.stl\");\n"

    fullposed_scad_path = "results/29_" + str(aiEngineName) + "_fullposed.scad"
    any_posed_changed |= _write_if_changed(
      fullposed_scad_path, scad_format.format(fullposed_scad_content, vc.formatConfig))

    if bugs == "" and (any_posed_changed
                       or not os.path.exists("results/29_" + str(aiEngineName) + "_fullposed.stl")):
      try:
        subprocess.run([
          vc.openScadPath, "29_" + str(aiEngineName) + "_fullposed.scad", "-o",
          "29_" + str(aiEngineName) + "_fullposed.stl"
        ],
                       cwd="results")
      except Exception as e:
        bugs += "OpenSCAD failed to generate fullposed STL for " + str(
          aiEngineName) + " due to " + str(e) + "<br>"

    # Basic validation: Correct number of parts, and non-zero sized stl files.
    if len(answer["parts"]) != 10:
      bugs += "Expected 10 parts, got " + str(len(answer["parts"])) + "<br>"

    for partIndex, part in enumerate(answer["parts"]):
      partName = "29_" + str(partIndex) + "_" + str(aiEngineName)
      stlFile = "results/" + partName + ".stl"

      if not os.path.exists(stlFile):
        bugs += "Part " + str(stlFile) + " does not exist<br>"
        continue

      # check file size is not 0
      if os.path.getsize(stlFile) == 0:
        bugs += "Part " + str(stlFile) + " was empty<br>"

      volume = vc.StlVolume.calculate_stl_volume(stlFile)
      print(partName + " Volume: " + str(volume))
      if volume == 0:
        bugs += "Part " + str(partIndex) + ".stl had a volume of 0<br>"

      # Mesh integrity checks (watertight, manifold)
      try:
        mesh = trimesh.load(stlFile, force='mesh')
      except Exception as e:
        bugs += f"Part {partIndex}.stl could not be parsed by trimesh: {e}<br>"
        continue

      if mesh.is_empty:
        bugs += f"Part {partIndex}.stl is empty geometry<br>"

      if not mesh.is_watertight:
        bugs += f"Part {partIndex}.stl is not watertight (must be a closed solid)<br>"

      if not mesh.is_winding_consistent:
        bugs += f"Part {partIndex}.stl has inconsistent face winding<br>"

      # Non-manifold detection (multiple bodies or problematic edges)
      if hasattr(mesh, "edges_nonmanifold"):
        non_manifold_edges = len(mesh.edges_nonmanifold)
      else:
        non_manifold_edges = 0

      if non_manifold_edges > 0:
        bugs += f"Part {partIndex}.stl has {non_manifold_edges} non-manifold edges<br>"

      if mesh.body_count and mesh.body_count > 1:
        bugs += f"Part {partIndex}.stl contains multiple disjoint solids ({mesh.body_count})<br>"

      if hasattr(mesh, "is_volume") and mesh.is_volume is False:
        bugs += f"Part {partIndex}.stl is not a valid closed volume<br>"

    earlyFail = bugs != ""
    return 0 if earlyFail else 1, bugs

  if earlyFail == True:
    return 0, "Failed as prerequestite test has failed."

  if subPass == 1:
    # Does it fit in the build volume?
    score = 0
    bugs = ""
    for partIndex, part in enumerate(answer["parts"]):
      partName = "29_" + str(partIndex) + "_" + aiEngineName
      stlFile = "results/" + partName + ".stl"

      overFlowsFromBuildVolume = vc.hit_tests(
        stlFile, ["translate([0,0,25]) cube([400,400,50], center=true)"], "difference")

      if overFlowsFromBuildVolume[0] == True:
        bugs += "Part " + str(
          partIndex) + ".stl does not fit in build volume or intersects with the floor<br>"
      else:
        score += 0.1

      # Printability: ensure model rests on bed with meaningful contact patch
      try:
        mesh = trimesh.load(stlFile, force='mesh')
      except Exception as e:
        bugs += f"Part {partIndex}.stl could not be parsed by trimesh for printability checks: {e}<br>"
        continue

      min_z = mesh.bounds[0, 2]
      if min_z < -0.1:
        bugs += f"Part {partIndex}.stl sits below the build plate (min z={min_z:.3f})<br>"

      # Faces intersecting z in [-0.1, 0.1]
      verts = mesh.vertices
      face_verts = verts[mesh.faces]
      face_min_z = face_verts[:, :, 2].min(axis=1)
      face_max_z = face_verts[:, :, 2].max(axis=1)
      contact_mask = (face_min_z <= 0.1) & (face_max_z >= -0.1)
      contact_area = float(np.sum(
        mesh.area_faces[contact_mask])) if mesh.area_faces is not None else 0.0

      # Require a reasonable contact patch (mm^2). Adjust threshold conservatively to avoid false positives.
      if contact_area < 500.0:
        bugs += f"Part {partIndex}.stl has insufficient bed contact area (~{contact_area:.1f} mm^2); may topple or not adhere<br>"

      # Overhang / floating geometry check: flag large downward-facing patches without support.
      normals = mesh.face_normals

      overhang_mask = normals[:, 2] < -0.9
      if np.any(overhang_mask):
        face_indices = np.nonzero(overhang_mask)[0]
        try:
          overhang_submeshes = mesh.submesh([face_indices], append=False, repair=False)
        except Exception:
          overhang_submeshes = []

        for sub in overhang_submeshes:
          # Bounding box extents in XY to approximate bridge span
          span = sub.bounds[1] - sub.bounds[0]
          span_xy = span[0:2]
          span_max = float(np.max(span_xy)) if len(span_xy) else 0.0
          area = float(sub.area)

          if sub.bounds[0][2] < 0.1:
            # Ignore overhangs which are actually just ground contact.
            continue

          # Allow small bridges/holes (e.g., 6mm) by tolerating small spans and areas
          if span_max <= 8.0 and area <= 80.0:
            continue

          # Otherwise, flag as problematic overhang
          bugs += (
            f"Part {partIndex}.stl has a large unsupported overhang/bridge (span ~{span_max:.1f} mm, area ~{area:.1f} mm^2); "
            "likely needs support.<br>")
          break

    return score, bugs

  if subPass == 2:
    # Does it have the correct gap between bars?
    tests4 = []
    tests10 = []

    def randomFloat(min, max):
      return random.uniform(min, max)

    intersectionTestCount = 100

    for i in range(intersectionTestCount):
      tests4.append(
        f"translate([{randomFloat(-120,120)},{randomFloat(-120,120)},0]) cube([40,40,40], center=true);"
      )
      tests10.append(
        f"translate([{randomFloat(-160,160)},{randomFloat(-160,160)},0]) cube([101,101,40], center=true);"
      )

    for partIndex, part in enumerate(answer["parts"]):
      partName = "29_" + str(partIndex) + "_" + aiEngineName
      stlFile = "results/" + partName + ".stl"
      results4 = vc.hit_tests(stlFile, tests4)
      results10 = vc.hit_tests(stlFile, tests10)

      if all(results4):
        bugs += "Part " + str(
          partIndex
        ) + ".stl always intersected a randomly placed 40mm cube. Gap between bars should be 50mm or higher.<br>"
      if not all(results10):
        bugs += "Part " + str(
          partIndex
        ) + ".stl allowed a 101mm cube to pass through. Gap between bars should be 100mm or lower.<br>"

      if bugs == "":
        for i in range(intersectionTestCount):
          if results4[i] == False:
            scad = "color(\"grey\") import(\"" + partName + ".stl\");\n" + tests4[i]
            scad = scad_format.format(scad, vc.formatConfig)
            vc.render_scadText_to_png(
              scad, "results/29_" + str(partIndex) + "_" + str(aiEngineName) + "_40mm.png")
            break

      if not all(results10):
        for i in range(intersectionTestCount):
          if results10[i] == False:
            scad = "color(\"grey\") import(\"" + partName + ".stl\");\n" + tests10[i]
            scad = scad_format.format(scad, vc.formatConfig)
            vc.render_scadText_to_png(
              scad, "results/29_" + str(partIndex) + "_" + str(aiEngineName) + "_101mm.png")
            break

    return 1 if bugs == "" else 0, bugs

  if subPass == 3:
    # Are the transform matrices correct and the cage is about the right size?
    tests = [
      "translate([0,0,360]) cube([340,340,680], center=true);",
      "translate([0,0,370]) difference() {cube([1000,1000,1000], center=true); cube([380,380,740], center=true);}",
    ]

    results = vc.hit_tests("results/29_" + str(aiEngineName) + "_fullposed.stl", tests)

    if results[0] == True:
      return 0, "Cage is too small or invalid transform matrices - a 350x350x700 needs to fit inside without intersecting the bars."
    if results[1] == True:
      return 0, "Cage is too large or invalid transform matrices - Cage must hold 350x350x700mm with 10mm thick bars"

    return 1, ""

  if subPass == 4:
    tests = [
      "translate([-180, -180, 0]) cylinder(d=5, h=360, center=true);",
      "translate([180, -180, 0]) cylinder(d=5, h=360, center=true);",
      "translate([-180, 180, 0]) cylinder(d=5, h=360, center=true);",
      "translate([180, 180, 0]) cylinder(d=5, h=360, center=true);",
      "translate([-180, -180, 0]) cylinder(r=8, h=360, center=true);",
      "translate([180, -180, 0]) cylinder(r=8, h=360, center=true);",
      "translate([-180, 180, 0]) cylinder(r=8, h=360, center=true);",
      "translate([180, 180, 0]) cylinder(r=8, h=360, center=true);",
    ]

    results = vc.hit_tests("results/29_" + str(aiEngineName) + "_fullposed.stl", tests)

    for i, result in enumerate(results[0:4]):
      if result == True:
        return 0, f"Error during simulated assembly: Unable to thread a 6mm rod through the cage segments (at {tests[i]}), it intersects the cage or bars."

    for i, result in enumerate(results[4:]):
      if result == False:
        return 0, f"Error during simulated assembly: Unable to use a 6mm rod through the cage segments (at {tests[i+4]}), it has so much clearence that a nut would just slide right through."

    return 1, ""

  if subPass == 5:
    for partIndexA, partA in enumerate(answer["parts"]):
      partNameA = "29_" + str(partIndexA) + "_" + aiEngineName
      stlFileA = "results/" + partNameA + "_posed.stl"
      tests = []
      for partIndexB, partB in enumerate(answer["parts"]):
        if partIndexA >= partIndexB:
          continue

        partNameB = "29_" + str(partIndexB) + "_" + aiEngineName
        stlFileB = "results/" + partNameB + "_posed.stl"
        tests.append("difference() {import(\"" + stlFileA + "\") ; import(\"" + stlFileB + "\");}")

      results = vc.hit_tests(stlFileA, tests)
      for i, result in enumerate(results):
        if result == True:
          # Find which part B corresponds to this test result
          partIndexB = i + partIndexA + 1  # Since we skip parts <= partIndexA
          return 0, "When assembled, part " + str(partIndexA) + " intersects with part " + str(
            partIndexB)

    return 1, ""

  if subPass == 6:
    bugs = ""
    for partIndexA, partA in enumerate(answer["parts"]):
      partNameA = "29_" + str(partIndexA) + "_" + aiEngineName
      stlFileA = "results/" + partNameA + "_posed.stl"

      tests = [
        "translate([-180, -180, 400]) cylinder(r=8, h=800, center=true);",
        "translate([180, -180, 400]) cylinder(r=8, h=800, center=true);",
        "translate([-180, 180, 400]) cylinder(r=8, h=800, center=true);",
        "translate([180, 180, 400]) cylinder(r=8, h=800, center=true);",
      ]

      results = vc.hit_tests(stlFileA, tests)
      intersectionCount = sum(results)
      if intersectionCount == 0:
        bugs += "When assembled, part " + str(
          partIndexA
        ) + " is not held in place by the threaded rods, and will fall out from the build when assembled.\n"

      if intersectionCount == 1:
        bugs += "When assembled, part " + str(
            partIndexA
        ) + " is only held in place by one threaded rod, allowing" \
        " it to rotate around a rod. Since the design brief said no doors or lids," \
        " such a part should not appear in the final design."

      scad = ""
      for i in range(4):
        if results[i] == True:
          scad += f"""
color("red") intersection() {{
{tests[i].replace('r=8','r=2')}
hull() {{
  translate([0,0,-50]) import("{partNameA}_posed.stl");
  translate([0,0,50]) import("{partNameA}_posed.stl");
}} 
}}
"""
      scad += "color(\"grey\") import(\"" + partNameA + "_posed.stl\");\n"
      scad = scad_format.format(scad, vc.formatConfig)
      vc.render_scadText_to_png(
        scad, "results/29_" + str(partIndexA) + "_" + str(aiEngineName) + "_6mm.png")

    return 1 if bugs == "" else 0, bugs

  if subPass == 7:
    # Verify bar thickness is ~10mm by measuring local thickness from large coplanar side facets.
    # End-caps of long bars (typically ~10mm x ~10mm) are ignored.
    bugs = ""
    tol_min = 9.5
    tol_max = 10.5
    min_span_ignore = 5.0
    endcap_span_max = 12.0
    min_facet_area = 30.0
    eps = 0.05
    samples_per_facet = 5
    min_thickness_samples = 25
    max_reasonable_thickness = 300.0
    hist_bin_width = 0.5
    min_mode_ratio = 0.15

    for partIndex, part in enumerate(answer["parts"]):
      partName = "29_" + str(partIndex) + "_" + aiEngineName
      stlFile = "results/" + partName + ".stl"
      if not os.path.exists(stlFile):
        bugs += f"Part {partIndex}.stl missing for thickness test<br>"
        continue

      try:
        mesh = trimesh.load(stlFile, force='mesh')
      except Exception as e:
        bugs += f"Part {partIndex}.stl could not be parsed for thickness test: {e}<br>"
        continue

      if mesh.is_empty:
        bugs += f"Part {partIndex}.stl empty geometry in thickness test<br>"
        continue

      # Ensure ray engine is available
      _ = mesh.ray

      facet_faces = getattr(mesh, "facets", None)
      facet_normals = getattr(mesh, "facets_normal", None)
      facet_areas = getattr(mesh, "facets_area", None)
      if facet_faces is None or facet_normals is None or facet_areas is None:
        bugs += f"Part {partIndex}.stl missing facet data for thickness test<br>"
        continue

      thickness_samples = []

      for facet_idx, faces in enumerate(facet_faces):
        area = float(facet_areas[facet_idx])
        if area < min_facet_area:
          continue

        n = facet_normals[facet_idx]
        # Only consider near-axis-aligned planar facets
        axis = int(np.argmax(np.abs(n)))
        if abs(n[axis]) < 0.9:
          continue

        # Compute facet bounds to decide if it's an end-cap or a side face
        tri = mesh.triangles[faces].reshape(-1, 3)
        bmin = tri.min(axis=0)
        bmax = tri.max(axis=0)
        span = bmax - bmin

        # Tangential spans (the two axes perpendicular to the facet normal axis)
        tangential_axes = [i for i in (0, 1, 2) if i != axis]
        t0 = float(span[tangential_axes[0]])
        t1 = float(span[tangential_axes[1]])

        # Ignore tiny patches (e.g., around holes or tiny chamfers)
        if min(t0, t1) < min_span_ignore:
          continue

        # Ignore end-caps of long bars: both tangential spans are ~10mm
        if t0 <= endcap_span_max and t1 <= endcap_span_max:
          continue

        # Sample a few points from the facet and measure thickness along inward normal
        centers = mesh.triangles_center[faces]
        if centers.shape[0] == 0:
          continue

        step = max(1, int(centers.shape[0] / samples_per_facet))
        sample_centers = centers[::step][:samples_per_facet]
        dists = []
        for c in sample_centers:
          origin = c - n * eps
          direction = -n
          loc, _, _ = mesh.ray.intersects_location([origin], [direction], multiple_hits=False)
          if len(loc) == 0:
            continue
          dist = float(np.dot(loc[0] - origin, direction))
          if dist > 0:
            dists.append(dist)

        if len(dists) == 0:
          continue

        thickness = float(np.median(dists))

        # Collect samples; final decision is based on robust statistics
        if thickness > eps and thickness < max_reasonable_thickness:
          thickness_samples.append(thickness)

      if len(thickness_samples) < min_thickness_samples:
        bugs += f"Part {partIndex}.stl did not produce enough thickness samples ({len(thickness_samples)}) for bar thickness test<br>"
        continue

      vals = np.asarray(thickness_samples, dtype=float)
      # Determine dominant thickness cluster (mode) using a histogram.
      # This avoids failing on rare large measurements caused by join divots / recess faces.
      bin_edges = np.arange(0.0, max_reasonable_thickness + hist_bin_width, hist_bin_width)
      hist, edges = np.histogram(vals, bins=bin_edges)
      mode_bin = int(np.argmax(hist))
      lo = float(edges[mode_bin])
      hi = float(edges[mode_bin + 1])
      mode_vals = vals[(vals >= lo) & (vals < hi)]
      mode_ratio = float(mode_vals.size) / float(vals.size) if vals.size else 0.0
      mode_est = float(np.median(mode_vals)) if mode_vals.size else float(np.median(vals))

      if mode_est < tol_min or mode_est > tol_max:
        bugs += (
          f"Part {partIndex}.stl bar thickness appears out of spec (dominant thickness ~{mode_est:.2f}mm, expected 10mm)<br>"
        )
        continue

      if mode_ratio < min_mode_ratio:
        bugs += (
          f"Part {partIndex}.stl bar thickness test inconclusive: dominant 10mm cluster too weak (mode ratio {mode_ratio:.2f})<br>"
        )
        continue

    if len(bugs) > 0:
      return 0, bugs

    return 1, f"{mode_ratio*100:.2f}% of solid bars span approx {mode_est:.2f}mm"

  if subPass == 8:
    # Verify bar gap spacing (50-100mm) by measuring air gaps between opposing bar side faces
    # in the assembled cage (fullposed).
    stlFile = "results/29_" + str(aiEngineName) + "_fullposed.stl"
    if not os.path.exists(stlFile):
      return 0, "Missing fullposed STL for gap spacing test<br>"

    try:
      mesh = trimesh.load(stlFile, force='mesh')
    except Exception as e:
      return 0, f"Could not parse fullposed STL for gap spacing test: {e}<br>"

    if mesh.is_empty:
      return 0, "Fullposed STL is empty in gap spacing test<br>"

    _ = mesh.ray

    # Sampling / filtering
    min_span_ignore = 5.0
    endcap_span_max = 12.0
    min_facet_area = 30.0
    eps = 0.2
    samples_per_facet = 5
    min_gap_samples = 50
    max_reasonable_gap = 250.0
    hist_bin_width = 1.0
    gap_tol_min = 50.0
    gap_tol_max = 100.0
    inlier_band = 5.0
    min_inlier_ratio = 0.20

    facet_faces = getattr(mesh, "facets", None)
    facet_normals = getattr(mesh, "facets_normal", None)
    facet_areas = getattr(mesh, "facets_area", None)
    if facet_faces is None or facet_normals is None or facet_areas is None:
      return 0, "Fullposed STL missing facet data for gap spacing test<br>"

    gap_samples = []
    for facet_idx, faces in enumerate(facet_faces):
      area = float(facet_areas[facet_idx])
      if area < min_facet_area:
        continue

      n = facet_normals[facet_idx]

      # Only consider near-axis-aligned facets in X or Y directions
      axis = int(np.argmax(np.abs(n)))
      if axis not in (0, 1):
        continue
      if abs(n[axis]) < 0.9:
        continue

      tri = mesh.triangles[faces].reshape(-1, 3)
      bmin = tri.min(axis=0)
      bmax = tri.max(axis=0)
      span = bmax - bmin

      tangential_axes = [i for i in (0, 1, 2) if i != axis]
      t0 = float(span[tangential_axes[0]])
      t1 = float(span[tangential_axes[1]])

      # Ignore tiny patches and end-caps (typically ~10mm x ~10mm)
      if min(t0, t1) < min_span_ignore:
        continue
      if t0 <= endcap_span_max and t1 <= endcap_span_max:
        continue

      centers = mesh.triangles_center[faces]
      if centers.shape[0] == 0:
        continue

      step = max(1, int(centers.shape[0] / samples_per_facet))
      sample_centers = centers[::step][:samples_per_facet]
      dists = []
      for c in sample_centers:
        origin = c + n * eps
        direction = n
        loc, _, _ = mesh.ray.intersects_location([origin], [direction], multiple_hits=False)
        if len(loc) == 0:
          continue
        dist = float(np.dot(loc[0] - origin, direction))
        if dist > 1.0 and dist < max_reasonable_gap:
          dists.append(dist)

      if len(dists) == 0:
        continue

      gap = float(np.median(dists))
      if gap > 1.0 and gap < max_reasonable_gap:
        gap_samples.append(gap)

    if len(gap_samples) < min_gap_samples:
      return 0, f"Gap spacing test did not produce enough samples ({len(gap_samples)})<br>"

    vals = np.asarray(gap_samples, dtype=float)
    bin_edges = np.arange(0.0, max_reasonable_gap + hist_bin_width, hist_bin_width)
    hist, edges = np.histogram(vals, bins=bin_edges)
    mode_bin = int(np.argmax(hist))
    lo = float(edges[mode_bin])
    hi = float(edges[mode_bin + 1])
    mode_vals = vals[(vals >= lo) & (vals < hi)]
    mode_est = float(np.median(mode_vals)) if mode_vals.size else float(np.median(vals))

    inlier_mask = np.abs(vals - mode_est) <= inlier_band
    inlier_ratio = float(np.sum(inlier_mask)) / float(vals.size) if vals.size else 0.0

    if mode_est < gap_tol_min or mode_est > gap_tol_max:
      return 0, f"Bar gap appears out of spec (dominant gap ~{mode_est:.2f}mm, expected 50-100mm)<br>"

    if inlier_ratio < min_inlier_ratio:
      return 0, f"Bar gap spacing not uniform enough (dominant gap ~{mode_est:.2f}mm, inlier ratio {inlier_ratio:.2f})<br>"

    return 1, f"Dominant bar gap ~{mode_est:.2f}mm (inlier ratio {inlier_ratio:.2f})"

  return 10000, "Nobody has gotten this far before... Need to write more parts of the test."


def resultToNiceReport(answer: dict, subPass: int, aiEngineName: str):
  if subPass == 0:
    return """
Checks to see if<ul>
<li> The correct number of parts are returned (10).</li>
<li> Whether the STL files exist and are non-zero sized.</li>
<li> Whether they are watertight.</li>
<li> Non self intersecting.</li>
<li> Fully connected</li><ul>
Some particully clueless AIs might generate 14 files (as 700mm/50mm == 14), 
which gets an instant 0 for wasting 4 prints
"""

  if subPass == 1:
    out = "Check to see if the parts are printable - resting on the z=0 plane, well supported, "\
      "not overhanging, and within print bounds:<br>"
    for partIndex in range(10):
      partName = "29_" + str(partIndex) + "_" + aiEngineName
      stlFile = "results/" + partName + ".stl"
      if os.path.exists(stlFile):
        vc.render_stl_to_png(stlFile, "results/" + partName + ".png")
        out += "<img src='" + partName + ".png' width=320/>"
    return out

  if subPass == 2:
    out = ""
    for partIndex in range(12):
      if os.path.exists("results/29_" + str(partIndex) + "_" + str(aiEngineName) + "_40mm.png"):
        out += "<img src='29_" + str(partIndex) + "_" + str(aiEngineName) + "_40mm.png' width=320/>"
      if os.path.exists("results/29_" + str(partIndex) + "_" + str(aiEngineName) + "_101mm.png"):
        out += "<img src='29_" + str(partIndex) + "_" + str(
          aiEngineName) + "_101mm.png' width=320/>"
    return out + """
<br>Check to see if the bars in cage segments are correctly sized and spaced. 
Can a 50mm cube pass through the bars? Does a 100mm cube get blocked? 100 random block positions
are checked, first pass is shown.
"""

  if subPass == 3:
    out = "Check to see if the part transform matrices are correct and the cage is correctly sized.<br>"

    if os.path.exists("results/29_" + aiEngineName + "_fullposed.stl"):
      vc.render_scadText_to_png("include<29_" + aiEngineName + "_fullposed.scad>",
                                "results/29_" + aiEngineName + "_fullposed.png")

      out += "<img src='29_" + aiEngineName + "_fullposed.png' width=640/>"

    return out

  if subPass == 4:
    return "Check to see if a 6mm threaded rod can fit through the cage segments holes.<br><br>" + \
      "(By testing whether a 5mm rod doesn't intersect, and an 8mm rod does intersect)<br><br>" + \
      "Since the dimensions are 350mm + 10mm sides + rod goes 'through the middle of the corner bar', " \
        "The rods position in 3D space must be exactly x =+/180, y=+-180,"

  if subPass == 5:
    return "Check to see if projected parts intersect each other - testing to see if all 90 combinations have 0 intersection volume."

  if subPass == 6:
    out = ""
    for partIndex in range(10):
      if os.path.exists("results/29_" + str(partIndex) + "_" + str(aiEngineName) + "_6mm.png"):
        out += "<img src='29_" + str(partIndex) + "_" + str(aiEngineName) + "_6mm.png' width=320/>"
    return out + "<br>Check to see if every part is connected via the rod, and that there's no "\
      "swinging or loose parts once the bolts are tightened."

  if subPass == 7:
    return "Check to see if every bar is 10mm thick (within tolerance). Opposing faces along X/Y/Z must be ~10mm apart."

  if subPass == 8:
    return "Check to see if the gap between cage bars is uniform and between 50mm and 100mm (measured on the assembled full cage)."


highLevelSummary = """
This is the hardest problem in here - turn a description of a large 3D model into printable 
parts that connect together without interfering.
<br><br>
Only one LLM has managed to even plan the split correctly yet.<br><br>

To be nice to the LLMs, we accept python, OpenSCAD, or STL format for the parts.<br><br>

A very suboptimal LLM might just divide the cage into 14 parts (as 700mm/50mm == 14),
which gets an instant 0 for wasting 4 prints.
<br><br>
The optimal split is 10 parts - top, bottom, and 2 segments each for the 
east, north, west and south. Each cage segment needs to make sure that the corner
bars are not double printed on adjacent segments, and each needs to make sure that the
6mm threaded rod can pass through tight enough that a nut would not slide right through.
"""

if __name__ == "__main__":
  import sys
  sys.path.append("placebo_data")
  import q29
  answer = q29.get_response(0)[0]
  gradeAnswer(answer, 0, "OpenSCAD")
  print(gradeAnswer(answer, 6, "OpenSCAD"))
  print(resultToNiceReport(answer, 6, "OpenSCAD"))
